### ISSUE TITLE
Add getters on `ModuleExports` for getting an Export via the exported thing's id

### ISSUE THREAD

**Issue by fitzgen** [rustwasm/walrus#113]
For example, getting the `Export` that is an exported function (ie has `ExportKind::Function`) via a function id.

```rust
impl ModuleExports {
    pub fn get_exported_func(&self, f: FunctionId) -> Option<&Export> { ... }
    pub fn get_exported_table(&self, f: TableId) -> Option<&Export> { ... }
    pub fn get_exported_memory(&self, f: TableId) -> Option<&Export> { ... }
    pub fn get_exported_global(&self, f: TableId) -> Option<&Export> { ... }
}
```

**Comment by lshlyapnikov** [comment]
@fitzgen how can I convert `FunctionId` and `TableId` to `ExportId`?
We have:
```
pub struct ModuleExports {
    /// The arena containing this module's exports.
    arena: TombstoneArena<Export>,
}
```
so, in order to fetch an export from the arena, I need an `ExportId`. Unless you want to iterate or have separate arenas for functions and tables.

**Comment by lshlyapnikov** [comment]
Or maybe we can accumulate the `FunctionId -> ExportId` and `TableId -> ExportId` mappings as part of the `add`:
```
    /// Add a new export to this module
    pub fn add(&mut self, name: &str, item: impl Into<ExportItem>) -> ExportId {
        self.arena.alloc_with_id(|id| Export {
            id,
            name: name.to_string(),
            item: item.into(),
        })
    }
```
I think I will implement this. Let me know if there is any other/better solution.

**Comment by lshlyapnikov** [comment]
@fitzgen I also believe you meant:
```
impl ModuleExports {
    pub fn get_exported_func(&self, f: FunctionId) -> Option<&Export> { ... }
    pub fn get_exported_table(&self, f: TableId) -> Option<&Export> { ... }
    pub fn get_exported_memory(&self, f: MemoryId) -> Option<&Export> { ... }
    pub fn get_exported_global(&self, f: GlobalId) -> Option<&Export> { ... }
}
```
the type of `f` argument for the last two functions.

**Comment by fitzgen** [comment]
> @fitzgen I also believe you meant:

Yes -- good eye!

> I think I will implement this. Let me know if there is any other/better solution.

Sounds great!

**Comment by lshlyapnikov** [comment]
@fitzgen not sure if you got notified... please have a look at this comment: https://github.com/rustwasm/walrus/pull/115#issuecomment-521487860

**Comment by lshlyapnikov** [comment]
@fitzgen this issue can be closed. #115 has been merged.

**Comment by fitzgen** [comment]
Thanks for the heads up!
