### ISSUE TITLE
Exposing LocalFunction::new as public

### ISSUE THREAD

**Issue by bkolobara** [rustwasm/walrus#186]
I want to modify a WASM file by swapping some imported functions for locally defined ones. It turns out this is not as easy to do with Walrus as I expected.

One approach would be to create local functions for each corresponding import and then loop through **all the code** and swap calls to imports with calls to the newly created local functions. This looks like a lot of unnecessary work.

Ideally I would do something like this:

```rust 
let mut local_function_builder = walrus::FunctionBuilder::new(...);
let local_function = walrus::LocalFunction::new(..., builder);
imported_function.kind = FunctionKind::Local(local_function);
``` 

In this case `imported_function` would keep the same id and we don't need to update all the call sites. This pattern looks ok to me, but the only issue is that `LocalFunction::new` is private and it's impossible to create directly LocalFunctions.

Are there some safety concerns I'm overlooking in exposing `LocalFunction::new` publicly?

**Comment by alexcrichton** [comment]
Seems reasonable to me! I think it may be best as a method on `FunctionBuilder`, however, but otherwise seems fine to expose
