### ISSUE TITLE
Is this project being maintained?

### ISSUE THREAD

**Issue by plusvic** [rustwasm/walrus#241]
It has been two years since the last release and there are few open PRs that haven't received any feedback yet. I find this crate very useful for a project I'm working on, but I'm wondering whether I should take it as a dependency, as the future of this project seems uncertain.

Other active projects like https://github.com/rustwasm/wasm-bindgen depend on this crate, so I guess at some point the they will need new releases of `walrus`. Can the maintainers shed some light on the plans for this project?

**Comment by guybedford** [comment]
0.20.0 just went out, do give it a try.

**Comment by aled93** [comment]
Is it still true? Last commit was 6 month ago
