### ISSUE TITLE
Invalid debug offset invariant

### ISSUE THREAD

**Issue by guybedford** [rustwasm/walrus#247]
Replication instructions in https://github.com/rustwasm/wasm-bindgen/pull/3483#issuecomment-1594273805.

The last instruction address from https://github.com/rustwasm/walrus/blob/main/src/module/debug/dwarf.rs#L214 ends up being after the subsequent function end address in https://github.com/rustwasm/walrus/blob/main/src/module/debug/dwarf.rs#L210.

Basic logging provides:

```
Instruction offset: 4834
Instruction offset: 4852
Instruction offset: 4859
Instruction offset: 4869
Instruction offset: 4884
Instruction offset: 4888
Instruction offset: 4898
Instruction offset: 4908
Instruction offset: 4909
Address conversion: 10337 -> 4407 (- 365 = 4042)
Function end: 4042
```

Where the broken invariant is then that `4909 < 4042` does not hold.

I tested the original PR and it also throws the exact same assertion so this was not an issue with the rebasing.

We maintain separate offset tables for the functions and instructions, and in this case, the instruction offsets are not present so we are falling back to the new `None` path in the `convert_address` function (which was not a part of the original Gimli implementation this came from that instead errored).

Separately, it's worth noting there's a language translation issue in the implementation where `Instrument` is used instead of `Instruction`, which might help code understanding to know.

**Comment by Stefan-Hanke** [comment]
I'd like to tackle this - but beware I have not done system-level programming for quite some time. My main motivation is gaining experience in the rust ecosystem in general.

What I did so far:
- Replicated the issue locally - I was glad that the code-lldb VSCode extension worked without any other configuration on Windows, and that I found about that patch table in config.toml (neat stuff)
- Skimmed over DWARF v5 - never been that far down.
- ... yeah and then trying to understand line programs. The spec is a difficult read for me. I found some resources but yeah, need to bite through that.

I'll now go on with generating some ELF debug-built object files (I failed to cross-compile a _hello world_...) and then using [dwex](https://github.com/sevaa/dwex) in the hope of gaining insight.

I'd appreciate resources about line programs.

**Comment by guybedford** [comment]
@Stefan-Hanke good luck! As I say I suspect the issue is somewhere in the offset handling code landed in the original PR that added this work, the `None` path in convert_address did seem a bit odd to me. If you have any questions at all in looking into this, happy to help in any way I can.

**Comment by d3lm** [comment]
Is there any progress on this?

**Comment by squillace** [comment]
Is there anything we can do to help finish this off here? I'd love to have rust support in vscode: https://github.com/rustwasm/wasm-bindgen/issues/2389#issuecomment-1728543877

**Comment by guybedford** [comment]
@squillace I'll gladly review any contribution to a bug fix. This issue should still have the required context to investigate further.
