### ISSUE TITLE
module with multiple memories is not parsed

### ISSUE THREAD

**Issue by juntyr** [rustwasm/walrus#261]
When parsing the [transformer-6252.wasm](https://github.com/rustwasm/walrus/files/14430155/transformer-6252.zip) module file (which is produced when mapping the component model to several core modules and seems to include several trampolines), walrus produces the following error:

```
failed to parse code section

Caused by:
    unknown memory 4 (at offset 1077)
```

The `wasmparser::Validator` with the `multi_memory` feature enabled however says that this module is valid and I would thus expect the module to parse correctly.

I'm using `walrus` version 0.20.3.

**Comment by guybedford** [comment]
Perhaps try this with 0.21.0 and see if that helps.
