### ISSUE TITLE
Bump semantic version for additions to Instr or tag it #[non_exhaustive]

### ISSUE THREAD

**Issue by dfoxfranke** [rustwasm/walrus#274]
The 0.21.2 release of walrus broke semantic versioning by adding `ReturnCall` and `ReturnCallIndirect` variants to the `Instr` enum. Either this enum should be tagged as `#[non_exhaustive]`, or additions to it should be a semantic version bump.

**Comment by guybedford** [comment]
I've published a 0.21.3 with that fix thanks.
