### ISSUE TITLE
Add a `name` method to `FunctionBuilder`

### ISSUE THREAD

**Issue by fitzgen** [rustwasm/walrus#61]
This would set the function's name for use with the name section.

Right now the name lives in the `Function` itself, we would want to move that into the builder, and then expose a method on the builder for setting the name, and a getter on `Function` for getting its name.

See `src/function_builder.rs` and `src/functions/mod.rs`.

**Comment by fgimenez** [comment]
I'd like to give it a try @fitzgen

**Comment by fgimenez** [comment]
Where can i find `src/functions/mod.rs`? Also, which would be the best place to add tests for this functionality?

**Comment by fitzgen** [comment]
@fgimenez Sure thing!

Woops, I meant `src/module/functions/mod.rs`! https://github.com/rustwasm/walrus/blob/master/src/module/functions/mod.rs

I don't think we need to explicitly test this method so much as test it indirectly by using it instead of setting the `Function::name` property directly. Places like

* https://github.com/rustwasm/walrus/blob/master/src/module/functions/mod.rs#L294
* https://github.com/rustwasm/walrus/blob/master/src/module/functions/mod.rs#L337
* https://github.com/rustwasm/walrus/blob/master/src/module/functions/mod.rs#L49

**Comment by fgimenez** [comment]
@fitzgen ok, I've proposed #65 as a WIP please take a look, it adds the setter to `FunctionBuilder` and the getter to `Function`, but I don't know how to wire them together. AIUI, `FunctionBuilder` creates `LocalFunction`, how can I refer to the name value stored in a `FunctionBuilder` from a `Function`?

Thanks!
