### ISSUE TITLE
Provide APIs for working with custom sections

### ISSUE THREAD

**Issue by fitzgen** [rustwasm/walrus#75]
### Motivation

There are many custom sections that are important for different use cases, eg webidl bindings custom section or the linking custom sections. People should be able to read, write, and manipulate custom sections that `walrus` itself doesn't know about.

### Proposed Solution

```rust
trait CustomSection: Any + Send {
    fn name(&self) -> &'static str;

    fn emit(&self, cx: &mut EmitContext);
}

/// One of these will be in `Module`.
pub struct ModuleCustomSections { ... }

impl ModuleCustomSections {
    /// Take the raw bytes of an unparsed custom section out of this module, if present.
    pub fn take_raw(&mut self, name: &str) -> Option<Vec<u8>>;

    /// Insert the given custom section into the module.
    pub fn add<T>(&mut self, custom_section: T) -> CustomSectionId<T>
        where T: CustomSection;

    /// Gets the given custom section that was previously added or panics.
    pub fn get<T>(&self, id: CustomSectionId<T>) -> &T
        where T: CustomSection;
    pub fn get_mut<T>(&mut self, id: CustomSectionId<T>) -> &mut T
        where T: CustomSection;

    /// Iterate over custom sections.
    pub fn iter(&self) -> impl Iterator<&dyn CustomSection>;
    pub fn iter_mut(&self) -> impl Iterator<&mut dyn CustomSection>;
}
```

This way, we don't have to specify an API for parsing, instead we let consumers take the raw bytes, parse however they want, and optionally add custom sections back into the module for emitting (which we do need to know how to emit).

### Alternatives

We could make parsing part of the `CustomSection` trait. This would make it more complex and less flexible, however.

We could avoid any trait object at all, and just take and receive `Vec<u8>` for custom sections. This has the advantage of not needing to expose the encoder machinery publicly. However, this forces users to have somewhere else to stash the parsed custom sections while manipulating a module, or to keep re-parsing and re-serializing them.

------------

Thoughts @alexcrichton?

**Comment by alexcrichton** [comment]
Looks great to me! I suspect we'd also need to add `Sync` to the trait bounds but that's just a minor quibble. I'm totally fine iterating on this in-tree :)

**Comment by fitzgen** [comment]
I guess the trait's `emit` method could just be `fn (&self) -> Vec<u8>`, which would avoid the downsides I listed about making the trait object simpler, while also avoiding exposing the whole encoding machinery. I think I will do this.
