### ISSUE TITLE
Support multi-value proposal

### ISSUE THREAD

**Issue by fitzgen** [rustwasm/walrus#77]
### Motivation

The [multi-value proposal](https://github.com/WebAssembly/multi-value/blob/master/proposals/multi-value/Overview.md) is stage 3, and is getting pretty mature. We should support it.

Additionally, they will end up pretty heavily used by webidl-bindings.

### Proposed Solution

There are some tricky bits here. A single expression can produce multiple values now, so a single expression AST node can be the input to multiple other AST nodes, so we go from somethign that can be encoded as a tree to something that requires a DAG. The DAG must still be stack-y, however, so there are some constraints on where edges can be.

I propose that

* We annotate edges between expressions with an index of which value is being used. So if an expression E returns 3 values v<sub>0</sub>, v<sub>1</sub>, v<sub>2</sub>, and the second value v<sub>1</sub> is an input operand to expression F, we get an edge like `F ---1---> E`.

* We add a legalization pass that detects non-stack-y edges in the DAG and spills values to new locals as needed.

* By the time we emit, we assert that we don't ever see non-stack-y edges, and panic if we do.

### Alternatives

The main alternatives I can think of are:

1. Abandon our AST-based design and switch to basic blocks and CFGs. Then all these things are just SSA values and there isn't really much different between one return value and many. But now we have to implement relooper or some other method of structural analysis/recovery.

2. Implement hacks to special case multi return values in our IR and always immediately spill them into locals.

I think (1) is more work than this proposal and doesn't give us any clear gains over this proposal.

I think (2) is 🤮 and will lead to tech debt.

**Comment by alexcrichton** [comment]
Reading up on this again, another (radical) alternative would be to abandon the AST-based design but switch to instruction lists. That would make this crate basically parity-wasm plus ids for references and nicer APIs in general here and there.

I don't think wasm-bindgen itself at least has any need for an AST-based design, but @fitzgen do your crates using walrus leverage the AST aspect?

I'm not necessarily a huge fan of this but I thought of it and figured it'd be worth mentioning. It'd certainly make the implementation of walrus much easier but would make consumption for cases which want an AST significantly harder. I think that @fitzgen your proposal is what a compiler framework *would* do in any case, and it "feels correct" in that it's still easy to use and should map to wasm itself efficiently.

**Comment by fitzgen** [comment]
Pre-requisite: get `wasmparser` supporting multi-value by default: https://github.com/yurydelendik/wasmparser.rs/pull/103

**Comment by fitzgen** [comment]
> Reading up on this again, another (radical) alternative would be to abandon the AST-based design but switch to instruction lists.

So we talked about this a bit in our meeting yesterday, but to leave some notes here for posterity:

Instruction lists are pretty hard to work with. Consider the example of removing a single argument from a function call (say because we are rewriting a wasm-bindgen instrinsic and we no longer need the parameter). With an AST or SSA based design, you just remove the parameter and (possibly implicitly) do some DCE and it is like the argument and its expression tree never existed. With an instruction list, you have to do backwards abstract interpretation or something to figure out which instructions contributed to that argument.
