### ISSUE TITLE
Add `unwrap_*` methods to `FunctionKind` to unwrap each variant of the enum

### ISSUE THREAD

**Issue by fitzgen** [rustwasm/walrus#82]
Looking at https://github.com/rustwasm/wasm-bindgen/pull/1566 and seeing a bunch of stuff that could get cleaned up if we had such a method.

**Comment by Atul9** [comment]
@fitzgen I would like to take this up.

**Comment by fitzgen** [comment]
Great! Let me know if you have any questions :)
