### ISSUE TITLE
Add method to get an import's id by module/name pair

### ISSUE THREAD

**Issue by fitzgen** [rustwasm/walrus#84]
Imagining something like this:

```rust
impl ModuleImports {
    pub fn find(&self, module: &str, name: &str) -> Option<ImportId> {
        // ...
    }
}
```

It would help clean up some random code in https://github.com/rustwasm/wasm-bindgen/pull/1566

**Comment by EusebioDM** [comment]
I would like to give it a try.

Should I include tests?  If so should I add them to the imports.rs file or somewhere separate?

**Comment by fitzgen** [comment]
Great! All yours :)

I would include a simple unit test for sanity. It can be in a `tests` module that is `cfg(test)`ed, similar to what we do at the bottom of `src/tombstone_arena.rs`.

**Comment by EusebioDM** [comment]
@fitzgen I create #90 for the issues. I tried adding tests like you recommended but I couldn't find a way to create a module with imports without using a .wat file, so I make the test using WABT like the other tests.

**Comment by lightclient** [comment]
Are there still pending tasks for this issue or did #90 complete it?

**Comment by fitzgen** [comment]
#90 took care of it -- thanks for the heads up!
