### ISSUE TITLE
Return `ImportId` from `Module::add_import_*`

### ISSUE THREAD

**Issue by alexcrichton** [rustwasm/walrus#86]
We have a number of functions on `Module` which allow adding an imported item which registers it with both the imports section as well as the appropriate section the item goes into. Currently only the target item's ID is returned, but we should also return the `ImportId` in addition to the item's actual ID.

**Comment by c410-f3r** [comment]
This is my first time in `walrus` and I will try to work on this issue.

@alexcrichton Can you give more information? Like which files or structs should be examined or modified?

**Comment by alexcrichton** [comment]
Oh sure yeah! This is targeted at [these four functions](https://github.com/rustwasm/walrus/blob/236c2fadc3cc77aac91d9f2b5751528e9ff84b81/src/module/imports.rs#L161-L211) where they return things like `FunctionId` now, but instead it'd be great if they all returned `(FunctionId, ImportId)`

**Comment by c410-f3r** [comment]
@alexcrichton Thanks!
